<a href="https://colab.research.google.com/github/venkateshblks/DataScience-practice/blob/main/decision%20tree/XGBM_and_LGBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# First XGBoost model for Pima Indians dataset
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [6]:
# load data
dataset = loadtxt('pima-indians-diabetes.data.csv', delimiter=",")
# split data into X and y
X = dataset[:,0:8]
Y = dataset[:,8]
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [4]:
# split data into train and test sets
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)
X_train


array([[  3.   , 102.   ,  44.   , ...,  30.8  ,   0.4  ,  26.   ],
       [  1.   ,  77.   ,  56.   , ...,  33.3  ,   1.251,  24.   ],
       [  9.   , 124.   ,  70.   , ...,  35.4  ,   0.282,  34.   ],
       ...,
       [  0.   ,  57.   ,  60.   , ...,  21.7  ,   0.735,  67.   ],
       [  1.   , 105.   ,  58.   , ...,  24.3  ,   0.187,  21.   ],
       [  8.   , 179.   ,  72.   , ...,  32.7  ,   0.719,  36.   ]])

In [26]:
# fit model no training data
model = XGBClassifier()
model1 = XGBClassifier()
model.fit(X_train, y_train)
model1.fit(X,Y)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [28]:
# make predictions for test data
import numpy as np

y_pred = model.predict(X_test)
y_pred1=model1.predict(X)

print(np.mean(y_pred1==Y))
# predictions = [round(value) for value in y_pred]
np.mean(y_pred==y_test)



1.0


0.7283464566929134

In [29]:
# evaluate predictions
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 72.83%


***Light GBM***

In [30]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [31]:
# Importing the dataset
dataset = pd.read_csv('pima-indians-diabetes.data.csv')
# split data into X and y
X = dataset.iloc[:,0:8]
Y = dataset.iloc[:,8]


In [32]:

# Splitting the dataset into the Training set and Test set

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)


In [53]:
import lightgbm as lgb
d_train = lgb.Dataset(x_train, label=y_train)
d = lgb.Dataset(X, label=Y)
d_train

In [37]:
params = {}
params['learning_rate'] = 0.003
params['boosting_type'] = 'gbdt'
params['objective'] = 'binary'
params['metric'] = 'binary_logloss'
params['sub_feature'] = 0.5
params['num_leaves'] = 10
params['min_data'] = 50
params['max_depth'] = 10

In [38]:
clf = lgb.train(params, d_train, 100)

[LightGBM] [Info] Number of positive: 206, number of negative: 369
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000238 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 638
[LightGBM] [Info] Number of data points in the train set: 575, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.358261 -> initscore=-0.582920
[LightGBM] [Info] Start training from score -0.582920
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

In [60]:
clf1 = lgb.train(params, d, 500)

[LightGBM] [Info] Number of positive: 267, number of negative: 500
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000042 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 764
[LightGBM] [Info] Number of data points in the train set: 767, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.348110 -> initscore=-0.627359
[LightGBM] [Info] Start training from score -0.627359


In [61]:
y_pred1=clf1.predict(X)
predictions1 = [round(value) for value in y_pred1]
pd.DataFrame(predictions1).value_counts()
accuracy_score(Y, predictions1)

0.788787483702738

In [42]:
#Prediction
y_pred=clf.predict(x_test)
y_pred

array([0.43812292, 0.35214659, 0.44924207, 0.38766077, 0.32511792,
       0.35233603, 0.4403519 , 0.29722223, 0.33129174, 0.31549203,
       0.27658251, 0.35936362, 0.3195423 , 0.40663205, 0.30832361,
       0.28649455, 0.36159717, 0.4389358 , 0.43481024, 0.35382879,
       0.29938769, 0.37007244, 0.34072565, 0.29007051, 0.35709233,
       0.42881573, 0.29916757, 0.39210845, 0.29198777, 0.30560728,
       0.44398461, 0.31467065, 0.36158065, 0.43044679, 0.3742303 ,
       0.35951053, 0.29494193, 0.33596039, 0.35488395, 0.42125883,
       0.28649229, 0.41277426, 0.33136734, 0.3329726 , 0.34646583,
       0.36331863, 0.34214009, 0.36019483, 0.35615555, 0.37582623,
       0.40229468, 0.38095607, 0.33916929, 0.35815294, 0.34175651,
       0.37154327, 0.40367155, 0.34584715, 0.34533912, 0.31998332,
       0.40736911, 0.31406285, 0.36822606, 0.40072582, 0.3422226 ,
       0.42699516, 0.36988567, 0.30158275, 0.34708962, 0.40855636,
       0.32309459, 0.4216275 , 0.36543678, 0.31790536, 0.45176

In [51]:
predictions = [round(value) for value in y_pred]
pd.DataFrame(predictions).value_counts()


0    192
dtype: int64

In [52]:
accuracy = accuracy_score(y_test, predictions)
y_test


661    1
122    0
113    1
14     1
529    0
      ..
366    0
301    0
382    0
140    0
463    0
Name: 1, Length: 192, dtype: int64

In [48]:
accuracy

0.6822916666666666